### ISSUE TITLE
Add ignore from vscode

### ISSUE THREAD

**Issue by ThiagoYuri** [Minibrams/svg-path-morph#1]
Can I add an ignore in git regarding vscode?
to delete this folder
![image](https://user-images.githubusercontent.com/78873117/176466985-ef0212bb-39ea-40fa-afcd-b49c9cc6ad1a.png)

**Comment by Minibrams** [comment]
I usually include the `.vscode` since it provides correctly configured debug tasks out of the box - but I suppose the `settings.json` doesn't need to be there. Feel free to make a PR 😁

**Comment by ThiagoYuri** [comment]
Ok
