### ISSUE TITLE
Package is empty in 1.0.3

### ISSUE THREAD

**Issue by jotoh98** [Minibrams/svg-path-morph#4]
Hi, thanks a lot for your work on this package, you don't believe how much time and pain that saved me 👍🏽 

I tried installing the package via pnpm and checked out my sources only to find that the package contains no sources. You can also look up the sources on [npmjs.org](https://www.npmjs.com/package/svg-path-morph?activeTab=code): no source file, but rather a polluting prettierrc.

Right now, there is no other fix except installing 1.0.2. Please let me know if I can help any further 👋🏽

**Comment by Minibrams** [comment]
Whoops 😅 thanks for letting me know! Should be good again in ~~v1.0.4~~ v1.0.5 (without `.prettierrc`).

Great to hear it's of use to you - let me know if you build something cool with it, I'm keen on seeing what people come up with 😃

**Comment by jotoh98** [comment]
Thanks for replying so fast, nice to see it working again :) 

I'm currently experimenting with path transitions instead of keyframes when changing modes:

Default animation:
![out2](https://github.com/Minibrams/svg-path-morph/assets/31740413/1deb763c-f692-4fb0-9baf-f3ffa52f1531)

Interrupted with transitions:
![out-t](https://github.com/Minibrams/svg-path-morph/assets/31740413/abdd7fda-cc1b-4625-b5ba-e5db33e05858)

Closing as fixed in version 1.0.5
